### PR TITLE
Added unit testing documentation

### PR DESCRIPTION
**Pull request by sonata82**
Just a first draft, tell me if you think there is something missing.

### CODE REVIEW

**Comment by kay-schecker** [comment]
Thanks a lot! I'll review it.

**Comment by kay-schecker** [comment]
I've reviewed your PR, but i want to create a testing guide and some custom jasmine matchers to make testing easier. For that i created a new branch "test-guide" which is based on this PR.

Please see https://github.com/HarmoWatch/ngx-redux-core/blob/test-guide/docs/articles/testing-guide.md

**Comment by kay-schecker** [comment]
Closed

**Comment by Ryuno-Ki** [comment]
@kay-schecker Pro-tip: When you are at a page like your testing-guide and hit `y` on the keyboard, GitHub will change the url to include the commit. This way, the link stays active even if you later move the file somewhere else ;-)

**Pull request closed without merging**
